### ISSUE TITLE
createdAt not populating

### ISSUE THREAD

**Issue by gregoryturner** [matfish2/craft-activity-log#1]
** Versions **
Craft: 4
Activity Logs: Latest

**Describe the bug**
No data is being written to the createdAt field in the database. Therefore, no data is pulled back into the admin/control panel view, and the view is blank. Where is createdAt supposed to write to the DB?  

**To Reproduce**
Load the Activity Logs in the control panel
Following query fails because 'createdAt' is null: http://localhost:8888/admin?action=activity-logs/activity-log/data&query=%7B%7D&limit=10&ascending=0&page=1&byColumn=1&orderBy=createdAt&createdAt=&actionSegments=

**Expected behavior**

**Screenshots**
<img width="1615" alt="Screen Shot 2022-10-10 at 10 34 18 AM" src="https://user-images.githubusercontent.com/4227162/194890776-dd7bf418-c89f-41bb-8854-d5342e590b04.png">
<img width="2033" alt="Screen Shot 2022-10-10 at 10 34 47 AM" src="https://user-images.githubusercontent.com/4227162/194890794-3b559d92-4a09-421e-8dad-9efb05bd529f.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 11.7
 - Browser Chrome, Firefox

**Smartphone (please complete the following information):**

**Additional context**
We're super interested in using this plugin for our healthcare website. However, this bug needs to be corrected.

**Comment by matfish2** [comment]
Thanks for reporting.
Apparently the default DB value for `createdAt` is set to `current_timestamp()`, but this is clearly unreliable.
I have added an explicit reference to current timestamp in code, and tested.
Version 1.1.1.
Would appreciate if you can confirm the fix works for you.

**Comment by gregoryturner** [comment]
Confirmed! I have updated the plugin in my local development environment and it appears to be functioning as intended. Thank you for the rapid response!
