### ISSUE TITLE
If any action perform outside the page then that action can't store in activity log

### ISSUE THREAD

**Issue by ks-arshitk** [matfish2/craft-activity-log#11]
** Versions **
Craft: 3.6.12.1
Activity Logs: 0.1.8

**Question**
-  First select Any menu
-  Select any entry
-  perform any action in action menu
![image](https://github.com/matfish2/craft-activity-log/assets/125453087/b1cb648d-6ada-4814-b019-9d10252b8ca8)

If any action perform outside the details page then that action can't store in activity log

**Activity setting**
![image](https://github.com/matfish2/craft-activity-log/assets/125453087/a17e94e4-3631-4d56-88f4-cb57420408c4)

Thank you

**Comment by matfish2** [comment]
@ks-arshitk I don't understand which action you are referring to.
What is the **request** associated with the action? The plugin doesn't record UI actions.
Note that your settings only record non-ajax actions. To record all CP action you need to check the "Record Control Panel AJAX Requests" as well.

**Comment by ks-arshitk** [comment]
@matfish2 I already enable "Record Control Panel AJAX Requests" and it store that request.
But there is problem, it store all ajax request and database size increase or in table it show all ajax entry or find any specific entry is difficult.

Is there any way to store specific entry ?

**Comment by matfish2** [comment]
>Is there any way to store specific entry ?
Yes. Use the `requestFilter` setting. It allow you to fine-tune the exact requests you wish to record.
See docs.

**Comment by matfish2** [comment]
Apologies, forgot you are using Craft 3. Request filtering is only available on Craft 4. I will add it to Craft 3 in the near future.

**Comment by matfish2** [comment]
Forgot you were using Craft 3. Added `requestFilter` on version 0.1.9.

**Comment by ks-arshitk** [comment]
I am showing list of request stored on Database to Front end, but initially all the stored request are shown, which is causing extra load for me, what I want, is to filter request list on initial page load

**Comment by matfish2** [comment]
@ks-arshitk if I understand correctly you still want those requests stored to the DB, but you want to filter on initial page load?
Because if you are not interested in storing the requests in the first place you can use the `requestFilter` function as indicated above.

**Comment by ks-arshitk** [comment]
@matfish2 I want to store two types of request but display one type of request to user.

**Comment by matfish2** [comment]
You can filter after page is loaded.
I may be able to add a "save state" button so that subsequent page loads will apply the same filter on initial load. I'll consider it.

**Comment by ks-arshitk** [comment]
@matfish2 
> so i don't want show to user.

Users means Admin

**Comment by matfish2** [comment]
But you still want those requests recorded for another user (the Developer), right? 
This would require something like a `filterRequestViewing` function/setting, that accepts the current user and returns a modified initial query. Need to think about it.

**Comment by ks-arshitk** [comment]
@matfish2 So what did you think about this?

**Comment by matfish2** [comment]
@ks-arshitk 
Please download v0.2.0 and try the following setting:
```
'viewFilters'=> [
        [
            'users'=>['admin'], // Username(s) of relevant users
            'filters'=>[ // Filters to be applied for said users
                'isCp'=>true, // Only Control Panel requests
                'isAction'=>true, // Only Action requests 
                'isAjax'=>false, // Only page Requests
                'siteId'=>1, // or (e.g) [1,2] for multiple sites
                'actions'=>[ // Only display those actions 
                    ['user-settings','save-group'] // full action array, can be found under `actionSegments` in `activitylogs` table
                ]
            ]
        ]
```

**Comment by ks-arshitk** [comment]
@matfish2 Where to write this code ?

**Comment by ks-arshitk** [comment]
@matfish2 
it show all the request

please check it
```
'viewFilters'=> [[
        'users'=>[],
        'filters'=>[
            'isCp'=>true,
            'isAction'=>true,
            'isAjax'=>true,
            'siteId'=>1,
            'actions'=>[
                ["Login"]
            ]
        ]
]],
```

**Comment by matfish2** [comment]
@ks-arshitk:
a. You didn't specify any `users` in the array. You need to give it at least one username (e.g `admin`). You can find the username under Users in Craft.
b. There is no `["Login"]` action. Action is called `["users","login"]`. It must match the `activitylog.actionSegements` column in the DB.

**Comment by ks-arshitk** [comment]
@matfish2 Thank you. It's work :+1:
