### ISSUE TITLE
Use of undefined constant JSON_THROW_ON_ERROR (PHP 7.2)

### ISSUE THREAD

**Issue by ks-arshitk** [matfish2/craft-activity-log#12]
** Versions **
Craft:3.6.12.1
Activity Logs: 0.2.0
PHP: 7.2.24

**Describe the bug**
I get following error while open activity log page

`{
    "error": "Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP)",
    "exception": "yii\\base\\ErrorException",
    "file": "/yk/prod/vendor/matfish/craft-activity-log/src/services/ApplyFiltersPerViewer.php",
    "line": 113,
    "trace": [
        {
            "file": "/yk/prod/vendor/craftcms/cms/src/web/ErrorHandler.php",
            "line": 77,
            "function": "handleError",
            "class": "yii\\base\\ErrorHandler",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/matfish/craft-activity-log/src/services/ApplyFiltersPerViewer.php",
            "line": 113,
            "function": "handleError",
            "class": "craft\\web\\ErrorHandler",
            "type": "->"
        },
        {
            "function": "matfish\\ActivityLog\\services\\{closure}",
            "class": "matfish\\ActivityLog\\services\\ApplyFiltersPerViewer",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/matfish/craft-activity-log/src/services/ApplyFiltersPerViewer.php",
            "line": 114,
            "function": "array_map"
        },
        {
            "file": "/yk/prod/vendor/matfish/craft-activity-log/src/services/ApplyFiltersPerViewer.php",
            "line": 42,
            "function": "applyFilter",
            "class": "matfish\\ActivityLog\\services\\ApplyFiltersPerViewer",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php",
            "line": 47,
            "function": "apply",
            "class": "matfish\\ActivityLog\\services\\ApplyFiltersPerViewer",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/matfish/craft-activity-log/src/controllers/ActivityLogController.php",
            "line": 26,
            "function": "retrieve",
            "class": "matfish\\ActivityLog\\services\\VueTablesActivityLogRetriever",
            "type": "->"
        },
        {
            "function": "actionData",
            "class": "matfish\\ActivityLog\\controllers\\ActivityLogController",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/yiisoft/yii2/base/InlineAction.php",
            "line": 57,
            "function": "call_user_func_array"
        },
        {
            "file": "/yk/prod/vendor/yiisoft/yii2/base/Controller.php",
            "line": 181,
            "function": "runWithParams",
            "class": "yii\\base\\InlineAction",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/craftcms/cms/src/web/Controller.php",
            "line": 190,
            "function": "runAction",
            "class": "yii\\base\\Controller",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/yiisoft/yii2/base/Module.php",
            "line": 534,
            "function": "runAction",
            "class": "craft\\web\\Controller",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/craftcms/cms/src/web/Application.php",
            "line": 274,
            "function": "runAction",
            "class": "yii\\base\\Module",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/craftcms/cms/src/web/Application.php",
            "line": 577,
            "function": "runAction",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/craftcms/cms/src/web/Application.php",
            "line": 253,
            "function": "_processActionRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/yk/prod/vendor/yiisoft/yii2/base/Application.php",
            "line": 392,
            "function": "handleRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/yk/prod/web/index.php",
            "line": 21,
            "function": "run",
            "class": "yii\\base\\Application",
            "type": "->"
        }
    ]
}`

@matfish2 **I think following code should be work**
**change in following code**
file : ApplyFiltersPerViewer.php
line : 112

`function ($action) {
       return "'" . json_encode($action, JSON_THROW_ON_ERROR) . "'";
}, $value);`

should be

`function ($action) {
       try {
             return "'" . json_encode($action) . "'";
       }catch(Exception $e) {
             return $e;
       }
}, $value);`

**Comment by matfish2** [comment]
@ks-arshitk please share your `viewFilters` settings.
This error indicates the the input might be incorrect.

**Comment by ks-arshitk** [comment]
@matfish2 
No, input was correct
It is working properly in php 7.4
error in php 7.2

'viewFilters'=> [[
        'users'=>['service-admin','adam@example.com'],
        'filters'=>[
            'actions'=>[ // Only display those actions
                ["users","save-user"], // full action array, can be found under `actionSegments` in `activitylogs` table
                ["users","delete-user"],
                ["element-indexes","perform-action"],
                ["elements","save-element"]
            ]
        ]
    ]],

**Comment by matfish2** [comment]
@ks-arshitk please try version 0.2.1

**Comment by ks-arshitk** [comment]
@matfish2 okay

**Comment by ks-arshitk** [comment]
@matfish2 yes, it's work
Thank you for responding so quickly.
