### ISSUE TITLE
All action can't show in action filter drop-down

### ISSUE THREAD

**Issue by ks-arshitk** [matfish2/craft-activity-log#13]
Craft: 3.6.12.1
Activity Logs: 0.2.1
PHP: 7.2

All action option can't show in action filter drop-down option. Is there any way to show all option in drop-down

**Screenshots**
![image](https://github.com/matfish2/craft-activity-log/assets/125453087/a1bec933-6666-4c77-ae86-5e9ce4e08fcf)

**Comment by ks-arshitk** [comment]
@matfish2 Is there any way to change default drop-down to custom drop-down ?

**Comment by matfish2** [comment]
@ks-arshitk on the Craft 3 version only **named** actions are displayed.
In order to be able to filter the action, you should go to the Actions page first and assign a name to the action.
E.g "Update Course Progress"

In Craft 4 version unnamed actions are automatically named, based on a convention.

**Comment by ks-arshitk** [comment]
@matfish2 In craft3, i can't see action tab

![image](https://github.com/matfish2/craft-activity-log/assets/125453087/c3df3c73-b828-407f-8739-455fb0b8de62)

**Comment by matfish2** [comment]
@ks-arshitk in Craft 3 it is under Settings->Activity Logs

**Comment by ks-arshitk** [comment]
@matfish2 
Activity Logs : v0.2.1

There is nothing like action, Can you share screen shot

![image](https://github.com/matfish2/craft-activity-log/assets/125453087/3c054c4c-13d5-42b9-bab4-4ffdabad6dd4)

**Comment by matfish2** [comment]
Apologies. @ks-arshitk, I forgot adding actions UI was only added on Craft 4. I don't have plans of adding it to Craft 3.

**Comment by matfish2** [comment]
@ks-arshitk can you please try version 0.2.2

**Comment by ks-arshitk** [comment]
@matfish2 
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'craft_actionSegments' in 'field list'\nThe SQL being executed was: SELECT `craft_actionSegments`\nFROM `craft_activitylog`\nWHERE `craft_actionSegments` IS NOT NULL\nGROUP BY `craft_actionSegments

I check in database and there is `actionSegments` column.

**Comment by matfish2** [comment]
@ks-arshitk  Fixed.
Please can you try 0.2.3

**Comment by ks-arshitk** [comment]
@matfish2 Thank you :+1:
