### ISSUE TITLE
Site filter not showing site name

### ISSUE THREAD

**Issue by strandofgenius** [matfish2/craft-activity-log#14]
When using env variables for the site name the site filter shows the variable rather than the site name.

<img width="227" alt="Screenshot 2024-07-25 at 3 44 16 PM" src="https://github.com/user-attachments/assets/cbb2e62c-01fc-4d17-bb96-4c54dd9d1965">

** Versions **
Craft: 5.2.6
Activity Logs: 2.0.0

**Comment by matfish2** [comment]
Thanks for reporting @strandofgenius 
Fixed in:

Craft 5: 2.0.1
Craft 4: 1.7.1
