### ISSUE TITLE
Error: Data too long for column 'ip'

### ISSUE THREAD

**Issue by robmcfadden** [matfish2/craft-activity-log#16]
** Versions **
Craft: 5.3.5
Activity Logs: 2.0.2

**Describe the bug**
Getting this error when visiting the login after plugin install.

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1 The SQL being executed was: INSERT INTO `activitylog` (`userId`, `url`, `query`, `payload`, `ip`, `userAgent`, `method`, `isAjax`, `isCp`, `siteId`, `isAction`, `actionSegments`, `createdAt`) VALUES (NULL, '/admin', NULL, NULL, '2a09:bac0:1001:48::000:00', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36', 'GET', 0, 1, 1, 0, NULL, '2024-08-26 14:47:13')An internal server error occurred.

There's a character limit of 20 on the ip column that doesn't accommodate the IPv6 address it's trying to pass in, it seems.

**Comment by matfish2** [comment]
Thank you for reporting @robmcfadden 
Should be resolved in 2.0.3

**Comment by kenlee-mirum** [comment]
Will there a same fix for Craft CMS 4?

**Comment by matfish2** [comment]
@kenlee-mirum fixed in 1.7.5
