### ISSUE TITLE
Throws "Not instantiable – yii\di\NotInstantiableException" error when trying to save new settings

### ISSUE THREAD

**Issue by gregoryturner** [matfish2/craft-activity-log#3]
** Versions **
Craft: 4
Activity Logs:  1.1.2

**Describe the bug**
When trying to activate "Record Only Actions" in the plugin settings screen, I get an error on save: 
```
Not instantiable – [yii\di\NotInstantiableException](https://www.yiiframework.com/doc-2.0/yii-di-notinstantiableexception.html)
Failed to instantiate component or class "function".
↵
Caused by: ReflectionException
Class "function" does not exist
in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 507
```

**To Reproduce**
1. Go to /admin/settings/activity-logs
2. Click on 'Record Only Action'
3. Click 'Save'

**Expected behavior**
It saves the new settings preferences.

**Screenshots**
Screenshots added, below

<img width="1396" alt="Screen Shot 2022-11-07 at 9 45 27 AM" src="https://user-images.githubusercontent.com/4227162/200348821-79c52075-688b-4045-92bc-acfdaf1900c6.png">
<img width="544" alt="Screen Shot 2022-11-07 at 9 45 16 AM" src="https://user-images.githubusercontent.com/4227162/200348823-2e3592c8-63cc-4508-bcce-9312ad5d5814.png">
<img width="538" alt="Screen Shot 2022-11-07 at 9 45 09 AM" src="https://user-images.githubusercontent.com/4227162/200348827-f9833e84-7794-4faf-b7bd-5de27a9cdf75.png">

**Desktop (please complete the following information):**
 - OS: Mac OS local development env. using Docker, NGINX, etc. 
 - Browser: Chrome
 - Version: 107.0.5304.87

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matfish2** [comment]
Thanks for reporting. Fixed in 1.1.3. Can you please confirm?
