### ISSUE TITLE
Can't install the Craft 3 version of the plugin when using PHP 7

### ISSUE THREAD

**Issue by angrybrad** [matfish2/craft-activity-log#7]
** Versions **
Craft: 3.8
Activity Logs: Latest Craft 3.x compatible version

It appears the Craft 3 version of the plugin uses PHP 8 syntax, so you'll get an error if you try to install the plugin on Craft 3.8 using PHP 7.x.

> syntax error, unexpected '|', expecting ';' or '{'

Craft 3 currently supports back to PHP 7.2.

The Craft 3 version of this plugin should either remove the PHP 8 syntax and support back to PHP 7.2.5 (the minimum Craft 3.8 supports) or add a Composer requirement that you need to run PHP 8 on Craft 3 if you want to use this plugin.

**Comment by matfish2** [comment]
Thanks @angrybrad. Fixed on version 0.1.5.
